In [15]:
import numpy as np

a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

print 'a=', a
print 'b=', b
print 'c=', c

a= [[ 0.61489389  0.92691653 -1.56382998]
 [ 0.69904363  0.73288941  1.46780552]]
b= [[ 0.95850106]
 [ 0.36412758]]
c= [[ 1.57339495  1.8854176  -0.60532891]
 [ 1.06317121  1.09701699  1.8319331 ]]


In [16]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
print 'a=', a
print 'b=', b
print 'c=', c

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [24]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

print c.shape


(12288L, 45L)


In [41]:
a = np.random.randn(3,4)
b = np.random.randn(4,1)
c = np.zeros((3,4))

for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]
    
print 'a=', a
print 'b=', b
print 'c=', c

print 'a + b.T', a + b.T

a= [[ 1.12416636 -0.40282351 -0.42940715 -0.08104071]
 [ 0.22719842 -0.86207711  0.79366055  1.6052962 ]
 [-0.14674353 -0.6992482   0.40607296 -0.79094261]]
b= [[-0.75276013]
 [ 1.71630119]
 [-0.65158585]
 [ 1.2302882 ]]
c= [[ 0.37140623  1.31347768 -1.08099301  1.14924749]
 [-0.52556171  0.85422408  0.14207469  2.8355844 ]
 [-0.89950366  1.01705298 -0.24551289  0.43934559]]
a + b.T [[ 0.37140623  1.31347768 -1.08099301  1.14924749]
 [-0.52556171  0.85422408  0.14207469  2.8355844 ]
 [-0.89950366  1.01705298 -0.24551289  0.43934559]]


In [42]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

print 'a=', a
print 'b=', b
print 'c=', c

a= [[-0.26608117 -0.31405324 -2.17902964]
 [-2.69278982 -0.8629026  -0.12443292]
 [ 0.04980799  0.21412945  0.24521517]]
b= [[ 0.14697054]
 [-0.31944335]
 [ 1.11026013]]
c= [[-0.03910609 -0.04615658 -0.32025317]
 [ 0.86019381  0.2756485   0.03974927]
 [ 0.05529982  0.2377394   0.27225263]]
